parameters:
#    c3_budget.example.class: C3\BudgetBundle\Example

services:
#    c3_budget.example:
#        class: %c3_budget.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
